### ISSUE TITLE
plot multiple serum samples on one graph

### ISSUE THREAD

**Issue by khdcrawford** [jbloomlab/neutcurve#16]
For analysis of neutralizing antibody dynamics, it is beneficial to plot multiple serum samples (generally different timepoints from one individual) on the same graph. Currently, it is possible to do this by making separate Hill curves for each sample and then specifying that they all plot on the same axis (such as below). This is a fine solution, but it would be great if there was a built-in function for overlaying neutralization curves for multiple serum samples on one graph as there currently is for overlaying curves for multiple viruses on one graph. 

Current code to achieve desired outcome: 

> curve1 = fits_byrow.getCurve(serum=sample_map[‘1’], virus=‘IDT_EK+pHAGE6’, replicate=‘1’)
> curve2 = fits_byrow.getCurve(serum=sample_map[‘2’], virus=‘IDT_EK+pHAGE6’, replicate=‘1’)
> fig, ax1 = curve1.plot(xlabel=‘dilution’)
> curve2.plot(ax=ax1, xlabel=‘dilution’, color=CBP[0])
> ax1.legend([sample_map[‘1’], sample_map[‘2’]], bbox_to_anchor=(1, 1))
> fig.show()

**Comment by jbloom** [comment]
Addressed in #22
