### ISSUE TITLE
Dose-response curve plot

### ISSUE THREAD

**Issue by zoehlerbz** [jbloomlab/neutcurve#27]
I work with alternative methods on animal use, more specifically using mesenchymal stem cells. Our lab analyses drugs toxicity growing cells under different drug concentrations. This allows us to generate a dose-response curve and determine some values like the IC50 and LD50 of these drugs, reducing the need of animals.

The problem is that we need GraphPad Prism software to generate the dose-response curve. And by using outsourced softwares, we have to manually explore and clean our data, which makes mistakes easier to happen. To solve this problem I started to study python to create an analysis code for our data.

After this long story, I finally get where I want. I'm using the "neutcurve" module in our code to generate the dose-response curve plot. The generated curve is impeccable (identical to the one generated by GraphPad). The only problem is the label plotted on the x-axis, referring to the concentrations. We use the logarithm of the concentrations, which are 2.0, 1.83, [...], 0.83 ug/ml. Because of this, the axis label appears only "10 ^ 0".

Is there a way to discriminate the concentration value on the x-axis?

**Comment by jbloom** [comment]
@zoehlerbz, Basically you just use standard `matplotlib` method for formatting the x ticks and their labels. In #28, I have added examples to the docs, which can now be viewed at the bottom of the following two pages:

When plotting a single curve from a `HillCurve` object: https://jbloomlab.github.io/neutcurve/hillcurve_example.html

When plotting multiple curves from a `CurveFits` object: https://jbloomlab.github.io/neutcurve/curvefits_example.html#additional-plot-customization
