### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by khdcrawford** [jbloomlab/neutcurve#29]
@jbloom I got a very similar error as previous folks mentioned when trying to use neutcurve in my new lasv_gp_dms environment. 

I think it has something to do with matplotlib not getting added to the environment properly or something? I also may have accidentally conda installed some things after pip installing other things, which I know can mess up environments. Anyway, I'll probably just try re-making the environment from my unpinned environment file, but there does seem to somewhat consistently be an issue with neutcurve and this matplotlib font thing.

```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-7c6a89b4525c> in <module>
      8 import numpy as np
      9 
---> 10 import neutcurve
     11 from neutcurve.colorschemes import CBPALETTE
     12 from neutcurve.colorschemes import CBMARKERS

~/miniconda3/envs/lasv_gp_dms/lib/python3.7/site-packages/neutcurve/__init__.py in <module>
     20 __url__ = 'https://github.com/jbloomlab/neutcurve'
     21 
---> 22 from neutcurve.curvefits import CurveFits  # noqa: F401
     23 from neutcurve.hillcurve import HillCurve  # noqa: F401

~/miniconda3/envs/lasv_gp_dms/lib/python3.7/site-packages/neutcurve/curvefits.py in <module>
     10 import math
     11 
---> 12 import dmslogo.facet
     13 import dmslogo.utils
     14 

~/miniconda3/envs/lasv_gp_dms/lib/python3.7/site-packages/dmslogo/__init__.py in <module>
     21 from dmslogo.facet import facet_plot  # noqa: F401
     22 from dmslogo.line import draw_line  # noqa: F401
---> 23 from dmslogo.logo import draw_logo  # noqa: F401

~/miniconda3/envs/lasv_gp_dms/lib/python3.7/site-packages/dmslogo/logo.py in <module>
     38 
     39 for _fontfile in matplotlib.font_manager.findSystemFonts(_FONT_PATH):
---> 40     matplotlib.font_manager.fontManager.addfont(_fontfile)
     41 for _fontfile in matplotlib.font_manager.findSystemFonts(None):
     42     try:

AttributeError: 'FontManager' object has no attribute 'addfont'
```

**Comment by khdcrawford** [comment]
Also, I think you know where my environment files are, but I can post them here if that's helpful, just let me know.

**Comment by jbloom** [comment]
Is this on server or on Mac?

**Comment by khdcrawford** [comment]
On the server.

**Comment by jbloom** [comment]
@khdusenbury, I suspect your problem was actually probably having an old version of `matplotlib`, but in any case should work now if you upgrade to newest `neutcurve` version.

**Comment by khdcrawford** [comment]
Thanks for the update! I guess I'm not quite sure why my new environment wouldn't install the latest matplotlib version, but thanks for the fix.
