### ISSUE TITLE
Get error estimate for curve-fitting

### ISSUE THREAD

**Issue by ajgreaney** [jbloomlab/neutcurve#32]
@jbloom We have discussed that it might be a good idea for `curvefits.CurveFits.fitParams()` to also return an error estimate for the curve fitting.

**Comment by ajgreaney** [comment]
@jbloom Just re-upping this request

**Comment by jbloom** [comment]
Sorry, I haven't forgotten. Not sure I will have enough concentrated time until next Tuesday when Alice is back in daycare though.
