### ISSUE TITLE
Additional data groupings in neutcurves

### ISSUE THREAD

**Issue by Bernadetadad** [jbloomlab/neutcurve#35]
Would it be possible to allow `CurveFits` to read additional columns in the data csv file that could be used for grouping data during the plotting of neutcurves?

 E.g in multiple projects now we have been using the `virus` column for things other than virus to group the data by, such as indicating if sera has been depleted or not depleted of RBD-binding mAbs. But sometimes we would like to group by additional variables, e.g. in addition to depleted/ non-depleted we would like to also like to indicate the cell type used. `CurveFits` just drops any non-default columns from the input dataframe, but maybe it would be possible to keep them and then use shape/colour/line-type to indicate additional variables on the plots?

**Comment by jbloom** [comment]
@Bernadetadad, this is possible in principle, but I'm not going to have time to implement in near future. The `plotGrids` method here has a lot of flexibility: https://jbloomlab.github.io/neutcurve/neutcurve.curvefits.html?highlight=curvefits#neutcurve.curvefits.CurveFits
