### ISSUE TITLE
Neutcurve occassionally fits curves that are not consistent with the data

### ISSUE THREAD

**Issue by anloes** [jbloomlab/neutcurve#43]
In some cases, neutcurve will find a fit for a replicate that is not the best fit for the data. The feature of the data which seems to exacerbate this issue is when the fraction infectivity for the highest dilution is found to be lower than the fraction infectivity calculated for the prior dilution. This will lead to negative slopes for the data. An example is included in figure attached. While the majority of the points for this curve overlap with those from the other replicates, the curve that is calculated is distinctly different. This issue may be resolved by adding a mechanism to specify whether neutcurve should allow calculation of curves with negative slope when fraction infectivity vs fraction neutralized is specified. 
![image](https://github.com/jbloomlab/neutcurve/assets/11932936/a00e3d3b-d926-4563-8abe-e2824cfcfac8)
[231220_NeutCurveError_FractionInfectivity_NegativeSlopeCurveFit.csv](https://github.com/jbloomlab/neutcurve/files/13733309/231220_NeutCurveError_FractionInfectivity_NegativeSlopeCurveFit.csv)

**Comment by jbloom** [comment]
Great, I will work on this. If you can find an example of one that incorrectly fits a flat curve then raise a separate issue for that and I will try to fix both at once.

**Comment by anloes** [comment]
I will pull the data for these in a minute, but these are not quite flat, but I suspect it may actually be the same issue, given that the curve is drawn with a negative slope, even though the data points don't quite merit that. 
![image](https://github.com/jbloomlab/neutcurve/assets/11932936/a6805df7-0113-44dd-8c46-e7f535997353)

**Comment by jbloom** [comment]
OK, I agree it may be the same issue looking at these. I vaguely thought I saw actual flat ones too paging through the data, but I wasn't paying super close attention so they could have just been ones like the orange curve on SerumB d0 as you note here.

**Comment by anloes** [comment]
I found one that is fully flat, recreating failure and will make new issue. It does seem like the topmost point is what is occasionally leading to a poor fit.  The leftmost curve here is not negatively sloped, but is biased towards fitting that topmost point over the rest of the data, as is occurring with the negative sloped curves above.
![image](https://github.com/jbloomlab/neutcurve/assets/11932936/461d77bc-7243-4a7d-9486-74363b14e646)
